services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: bankes-app:prod
    env_file:
      - .env
    ports:
      - "3031:3031"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    restart: unless-stopped
labels:
  - "traefik.enable=true"
  - "traefik.http.routers.bankes.rule=Host(`bankes.iom-itb.id`)"
  - "traefik.http.routers.bankes.entrypoints=websecure"
  - "traefik.http.routers.bankes.tls.certresolver=letsencrypt"
  - "traefik.http.services.bankes.loadbalancer.server.port=3031"

#  postgres:
#    image: postgres:17-alpine
#    env_file:
#     - .env
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#      interval: 5s
#      timeout: 2s
#      retries: 10
#      start_period: 5s
#    restart: unless-stopped

#  minio:
#    image: minio/minio:latest
#    env_file:
#      - .env
#    environment:
#      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
#      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
#      - MINIO_SERVER_URL=${MINIO_SERVER_URL:-http://localhost:9000}
#      - MINIO_BROWSER_REDIRECT_URL=${MINIO_CONSOLE_URL:-http://localhost:9001}
#    command: server /data --console-address ":9001"
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - minio-data:/data
#    healthcheck:
#      # test: ["CMD", "curl", "-f", "http://localhost:19000/minio/health/live"]
#      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    restart: unless-stopped

#  minio-init:
#    image: minio/mc:latest
#    env_file:
#      - .env
#    depends_on:
#      minio:
#        condition: service_healthy
#    volumes:
#      - ./minio-init.sh:/minio-init.sh
#    entrypoint: ["/bin/bash", "/minio-init.sh"]
#    restart: "no"

#volumes:
#  postgres-data:
#  minio-data:

