version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: iom-app
    ports:
      #      - "3031:3031"
      - "13031:3031"
    volumes:
      # Mount your source code for hot reload
      - ./:/app:delegated

      # Keep containerâ€™s node_modules persistent (avoid overwriting by bind mount)
      - ./node_modules:/app/node_modules

    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/db
      JWT_SECRET: HIDUPMAHASISWA
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: iom-itb
      AZURE_AD_CLIENT_ID: 399d7b9a-36a0-42ac-883b-b72485a32d79
      AZURE_AD_CLIENT_SECRET: mkE8Q~ACq6pSwVy3j4dHncFIijwEbzD_KyAHJaLC
      AZURE_AD_TENANT_ID: db6e1183-4c65-405c-82ce-7cd53fa6e9dc
      NEXTAUTH_SECRET: random
      NEXTAUTH_URL: http://localhost:3031

    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

    command: >
      bash -c "npx prisma migrate deploy &&
               npm run dev -- -p 3031"

    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: iom-postgres
    ports:
      #- "5432:5432"
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: iom-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":19001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  minio-init:
    image: minio/mc
    container_name: iom-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/minio-init.sh && /app/minio-init.sh"]
    volumes:
      - ./minio-init.sh:/app/minio-init.sh:ro
    restart: "no"

volumes:
  postgres-data:
  minio-data:
